name: Deploy to Firebase

on:
   push:
      branches:
         - master

jobs:
   deploy:
      runs-on: ubuntu-latest
      environment: production
      env:
         NODE_ENV: production
         VITE_NODE_ENV: production
         FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
         VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
         VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
         VITE_FIREBASE_DATABASE_URL: ${{ secrets.VITE_FIREBASE_DATABASE_URL }}
         VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
         VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
         VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
         VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
         VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}

      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Set up Node.js
           uses: actions/setup-node@v4
           with:
              node-version: '20'

         - name: Clean npm cache and remove lock and modules
           run: |
              npm cache clean --force
              rm -rf node_modules package-lock.json
              rm -rf functions/node_modules functions/package-lock.json

         - name: Install root dependencies
           run: npm install

         - name: Build frontend
           run: npm run build

         - name: Install functions dependencies
           working-directory: ./functions
           run: npm install

         - name: Build functions
           working-directory: ./functions
           run: npm run build

         - name: Install Firebase CLI
           run: npm install -g firebase-tools

         - name: Deploy to Firebase
           run: firebase deploy --non-interactive
